services:
  # ofelia.job-run.datecron.schedule: "5 0 8 * * *"
  reschedule-tasks:
    init: true
    image: ghcr.io/alexzasorin/that-what-must-be-done/app:latest
    container_name: reschedule-tasks
    command:
      [
        "--filter",
        "!assigned to:others & !no date & !recurring & no deadline & !p1",
        "--rules",
        "./app/rules.json",
        "--dry-run",
        "--time-zone",
        "US/Pacific",
        "--schedule",
        "* * * * *",
      ]
    volumes:
      - ~/.config/rescheduler/rules.json:/app/rules.json
    environment:
      - TODOIST_USER_TOKEN=${TODOIST_USER_TOKEN}
    networks:
      - default
  reschedule-recurring:
    init: true
    image: ghcr.io/alexzasorin/that-what-must-be-done/app:latest
    container_name: reschedule-recurring
    command:
      [
        "--filter",
        "!assigned to:others & !no date & overdue & recurring & no deadline & !p1",
        "--dry-run",
        "--time-zone",
        "US/Pacific",
        "--schedule",
        "* * * * *",
      ]
    volumes:
      - ~/.config/rescheduler/rules.json:/app/rules.json
    environment:
      - TODOIST_USER_TOKEN=${TODOIST_USER_TOKEN}
    networks:
      - default

networks:
  default:
