# This is my actual docker-compose file that I use to run the rescheduler service.
# Will eventually replace this with an example and move my personal one out.
name: postpwn
services:
  reschedule-tasks:
    init: true
    image: ghcr.io/alexzasorin/postpwn:latest
    container_name: reschedule-tasks
    command:
      [
        "--filter",
        "!assigned to:others & !no date & !recurring & no deadline & !p1",
        "--rules",
        "/app/rules.json",
        "--time-zone",
        "US/Pacific",
        "--schedule",
        "* * * * *",
        "--token",
        "${TODOIST_USER_TOKEN}",
      ]
    volumes:
      - ~/.config/rescheduler/rules.json:/app/rules.json
    environment:
      - TODOIST_USER_TOKEN=${TODOIST_USER_TOKEN}
  reschedule-recurring:
    init: true
    image: ghcr.io/alexzasorin/postpwn:latest
    container_name: reschedule-recurring
    command:
      [
        "--filter",
        "!assigned to:others & !no date & overdue & recurring & no deadline & !p1",
        "--time-zone",
        "US/Pacific",
        "--schedule",
        "* * * * *",
        "--token",
        "${TODOIST_USER_TOKEN}",
      ]
