services:
  ofelia:
    image: mcuadros/ofelia:latest
    init: true
    depends_on:
      - rescheduler
    command: daemon --docker
    container_name: ofelia
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.enabled: "true"
      ofelia.job-run.datecron.schedule: "5 0 0 * * *"
      ofelia.job-run.datecron.container: "rescheduler"
    networks:
      - default
  rescheduler:
    init: true
    image: ghcr.io/alexzasorin/that-what-must-be-done/app:latest
    env_file: .env
    container_name: rescheduler
    volumes:
      - ${CONFIG_PATH}:/app/rules.json
    environment:
      - CONFIG_PATH=${CONFIG_PATH}
    networks:
      - default

networks:
  default:
